server:
  port: 8084
MESSAGE: hi dev-2

spring:
  datasource:
    username: ${postgres_username}
    password: ${postgres_password}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://68.183.187.158:5432/postgres_db

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true